### ISSUE TITLE
crazyflie和动捕通讯

### ISSUE THREAD

**Issue by Gitzhaolong** [bitcraze/bitcraze-website#105]
你好，我想问下用国产的动捕NOKOV，怎么使用crazyswarm项目，我将swarm中的hover_swarm.launch修改成vrpn,ip地址设置为动捕服务器的，运行launch文件后显示找到动捕的track cf1和cf2，但是一直报错[ WARN] [1638455635.731827776]: No updated pose for motion capture object cf1，同时rostopic list中只有cf1/*，没有cf2/*，能帮忙回答一下吗

**Comment by krichardsson** [comment]
Hi! 
This repository is for the Bitcraze web site while your question seems to be related to Crazyswarm. Please try https://github.com/USC-ACTLab/crazyswarm instead
