### ISSUE TITLE
Crazyflie 2.0 getting started misses Zadig guide for the radio PA

### ISSUE THREAD

**Issue by wldevries** [bitcraze/bitcraze-website#16]
https://wiki.bitcraze.io/doc:crazyradio:install_windows_zadig

at least for me this was necessary and I had a hard time googling around..

**Comment by ataffanel** [comment]
Hi, thanks for reporting!
Did you need zadig to get the crazyradio working in the virtual machine or are you running with a native client on Windows?

**Comment by wldevries** [comment]
Yes I needed Zadig to be able to get it working in the VM. I'm using W10 with all updates applied. The device shows up as an unknown device and even though it shows up in the USB list for VirtualBox it won't be passed on to the VM if you enable it.

**Comment by ataffanel** [comment]
I tested and can confirm. I'll add a link to the wiki on the getting started.

Thanks!
