### ISSUE TITLE
broken link to SVD file

### ISSUE THREAD

**Issue by hmllr** [bitcraze/bitcraze-website#164]
Hi :)
on https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/development/openocd_gdb_debugging/ the link to the SVD file is unfortunately broken. I am not sure where to upload this file, that's why this is not directly a pull request :)
Thanks for fixing it,
Hanna

**Comment by knmcguire** [comment]
Thanks! we will fix it now

**Comment by knmcguire** [comment]
fixed with this https://github.com/bitcraze/crazyflie-firmware/pull/1356
