### ISSUE TITLE
Link on local distributor page to Elektor returns a 404 error

### ISSUE THREAD

**Issue by fredg02** [bitcraze/bitcraze-website#18]
On https://www.bitcraze.io/distributors/ the link to Elektor (https://www.elektor.com/crazyflie-2-0-full-kit) returns a 404. I've searched on their webpage for "crazyflie" and "bitcraze", but nothing was found. Seems like they don't carry the Crazyflie in their store anymore.

**Comment by krichardsson** [comment]
Will check. Thanks!
