### ISSUE TITLE
Share blog posts on Mastodon (automatically)

### ISSUE THREAD

**Issue by fredg02** [bitcraze/bitcraze-website#182]
I've noticed that I missed a lot of very interesting blog posts since I'm no longer using Twitter. I hope there is a somewhat easy way to share the blog posts on your Mastodon account. Maybe even automatically or with a single tool that publishes to different social media accounts (e.g. Twitter/Mastodon/etc) at the same time.

I promise to boost your toots. 🙂

**Comment by Bananazooka** [comment]
Hi Fred, 
Thanks for your support! Currently, we publish everything manually - and it's true that Mastodont is not in our current plan! We'll make sure we publish there from now on.
