### ISSUE TITLE
Organization of research papers on webpage

### ISSUE THREAD

**Issue by imciner2** [bitcraze/bitcraze-website#22]
I was looking through the paper listing on the research page and noticed that there doesn't appear to be an order to the listing (at least for the Crazyflie 2.0 section). The Crazyflie 1.0 section seems to be listed in reverse chronological order (e.g. 2012 on the top, 2015 on the bottom).

I have a thesis to add to the page, but I think it needs to have some sorting structure to it as well. I have seen similar listings done in chronological order (so most-recent at the top), and that also makes it fairly easy to update (simply add the new article/contribution to the top of the list). What are people's thoughts on this?

**Comment by krichardsson** [comment]
Hi!
chronological order sounds good to me

**Comment by imciner2** [comment]
Chronological ordering has been implemented in pull request #23.

**Comment by krichardsson** [comment]
Merged and published. Thanks!
