### ISSUE TITLE
Add failure mode LED code

### ISSUE THREAD

**Issue by TomBinford** [bitcraze/bitcraze-website#89]
https://www.bitcraze.io/documentation/tutorials/getting-started-with-crazyflie-2-x/
There is an additional LED code not mentioned on the above page. Should the crazyflie experience a memory leak (as I found out today) or presumably any other unrecoverable error, all four LEDs turn solid blue/red and the drone needs to be restarted.

**Comment by knmcguire** [comment]
Hi! sorry for the delayed answer.

Is this a state that would be experienced by a crazyflie first-timer? A memory leak seems more like there has been flashed an adapted firmware or an app layer on the Crazyflie, which is perhaps more of development instructions.  

I'm just thinking of the right place of where to put this information... we also have the trouble shooting page for instance: https://www.bitcraze.io/support/troubleshooting/

**Comment by TomBinford** [comment]
You're correct; I created the memory leak by mismanaging timers in a custom driver. This failure should only be encountered in a development scenario. I suggested adding to the "Understanding LEDs" section because my thought process on encountering this error was to first find out what the error code status meant. A Google search for "crazyflie LED codes" brought me to that page.
I agree with you that encountering this error isn't a "getting started" issue, but I also think it's a bad idea to have information about one LED code completely separated from the others. Perhaps that information could be duplicated on the Getting Started and Troubleshooting pages? On a page of its own? I don't have experience with documentation, so this is just my take, of course. Thank you!

**Comment by knmcguire** [comment]
It's a good point.. but currently we don't know exactly where this will fit. I'll keep this issue open to remind us to find a good place for it, as we are currently in the works with the website to clean it up

**Comment by knmcguire** [comment]
So technically this will be something that fits under the [ 'trouble shooting' guide](https://www.bitcraze.io/support/troubleshooting/#crazyflie-is-bricked) on the web under 'Crazyflie is bricked'. But I'll add some extra meaning to this as well to add that LED meaning.

**Comment by knmcguire** [comment]
merged with #110
